ecompress*: Remove implicit decompression

diff --git a/bin/ebuild-helpers/ecompressdir b/bin/ebuild-helpers/ecompressdir
--- a/bin/ebuild-helpers/ecompressdir
+++ b/bin/ebuild-helpers/ecompressdir
@@ -2,7 +2,7 @@
 # Copyright 1999-2018 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 
-source "${PORTAGE_BIN_PATH}"/helper-functions.sh || exit 1
+source "${PORTAGE_BIN_PATH}"/isolated-functions.sh || exit 1
 
 if [[ -z $1 ]] ; then
 	__helpers_die "${0##*/}: at least one argument needed"
@@ -65,22 +65,21 @@ done
 suffix=$(ecompress --suffix)
 
 # funk_up_dir(action, suffix, binary, [size_limit])
-#	- action: compress or decompress
+#	- action: compress
 #	- suffix: the compression suffix to work with
-#	- binary: the program to execute that'll compress/decompress
+#	- binary: the program to execute that'll compress
 #   - size_limit: if compressing, skip files smaller than this
 # The directory we act on is implied in the ${dir} variable
 funk_up_dir() {
 	local act=$1 suffix=$2 binary=$3 size_limit=$4
 
-	local negate=""
-	[[ ${act} == "compress" ]] && negate="!"
+	[[ ${act} == "compress" ]] || die "${FUNCNAME}: invalid action: ${act}"
 
 	local ret=0
 	# first we act on all the files
 	local args=(
 		-type f
-		${negate} -iname "*${suffix}"
+		! -iname "*${suffix}"
 	)
 	[[ -n ${size_limit} ]] && args+=( -size "+${size_limit}c" )
 	find "${dir}" "${args[@]}" -print0 | ${XARGS} -0 ${binary}
@@ -105,12 +104,7 @@ funk_up_dir() {
 			skip_dir_dest=${T}/ecompress-skip/${actual_dir#${ED%/}}/${brokenlink%/*}/${olddest}
 		fi
 		[[ -e ${skip_dir_dest} ]] && continue
-		if [[ ${act} == "compress" ]] ; then
-			newdest=${olddest}${suffix}
-		else
-			[[ ${olddest} == *${suffix} ]] || continue
-			newdest=${olddest%${suffix}}
-		fi
+		newdest=${olddest}${suffix}
 		if [[ "${newdest}" == /* ]] ; then
 			[[ -f "${D%/}${newdest}" ]] || continue
 		else
@@ -118,9 +112,7 @@ funk_up_dir() {
 		fi
 		something_changed=${brokenlink}
 		rm -f "${brokenlink}"
-		[[ ${act} == "compress" ]] \
-			&& ln -snf "${newdest}" "${brokenlink}${suffix}" \
-			|| ln -snf "${newdest}" "${brokenlink%${suffix}}"
+		ln -snf "${newdest}" "${brokenlink}${suffix}"
 		((ret|=$?))
 	done < <(find "${dir}" -type l -print0)
 	[[ -n ${something_changed} ]] || break
@@ -160,16 +152,6 @@ ret=0
 
 rm -rf "${T}"/ecompress-skip
 
-decompressors=(
-	".Z"    "gunzip -f"
-	".gz"   "gunzip -f"
-	".bz2"  "bunzip2 -f"
-	".xz"   "unxz -f"
-	".lzma" "unxz -f"
-)
-
-__multijob_init
-
 for dir in "$@" ; do
 	dir=${dir#/}
 	dir="${ED%/}/${dir#/}"
@@ -189,23 +171,6 @@ for dir in "$@" ; do
 	size_limit=${SIZE_LIMIT:-$(<"${actual_dir}.ecompress.dir")}
 	rm -f "${actual_dir}.ecompress.dir"
 	find "${dir}" -type f -name '*.ecompress.file' -print0 | ${XARGS} -0 rm -f
-
-	# not uncommon for packages to compress doc files themselves
-	for (( i = 0; i < ${#decompressors[@]}; i += 2 )) ; do
-		# It's faster to parallelize at this stage than to try to
-		# parallelize the compressors.  This is because the find|xargs
-		# ends up launching less compressors overall, so the overhead
-		# of forking children ends up dominating.
-		(
-		__multijob_child_init
-		funk_up_dir "decompress" "${decompressors[i]}" "${decompressors[i+1]}"
-		) &
-		__multijob_post_fork
-		: $(( ret |= $? ))
-	done
-
-	__multijob_finish
-	: $(( ret |= $? ))
 
 	# forcibly break all hard links as some compressors whine about it
 	find "${dir}" -type f -links +1 -exec env file="{}" sh -c \
